      - name: Call model API
        id: ask
        run: |
          body=$(jq -n --rawfile p prompt.txt \
            '{model:env.AI_MODEL,
              messages:[
                {role:"system",content:"Tu es un relecteur de code strict."},
                {role:"user",content:$p}
              ]}')
          resp=$(curl -sS -X POST "$AI_API_URL" \
            -H "Authorization: Bearer $AI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$body")
          echo "resp<<EOF" >> $GITHUB_OUTPUT
          echo "$resp"     >> $GITHUB_OUTPUT
          echo "EOF"       >> $GITHUB_OUTPUT
